import type { Metadata } from 'next'
import { MainLayout } from '@/components/layout'

export const metadata: Metadata = {
  title: 'Diff',
  description: 'View code changes generated by the AI agent.',
  openGraph: {
    title: 'Diff | Agent Board',
    description: 'View code changes generated by the AI agent',
  },
}

export default function DiffLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return <MainLayout>{children}</MainLayout>
}
