use serde::{Deserialize, Serialize};

/// All valid task statuses representing the lifecycle of a task in the two-agent system.
///
/// Primary workflow:
///   draft -> refining -> pending_approval -> approved -> coding -> plan_review -> review -> done
///
/// Legacy statuses are kept for backward compatibility.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum TaskStatus {
    // New two-agent workflow statuses
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "refining")]
    Refining,
    #[serde(rename = "pending_approval")]
    PendingApproval,
    #[serde(rename = "approved")]
    Approved,
    #[serde(rename = "coding")]
    Coding,
    #[serde(rename = "plan_review")]
    PlanReview,
    #[serde(rename = "review")]
    Review,
    #[serde(rename = "merge_conflicts")]
    MergeConflicts,
    #[serde(rename = "changes_requested")]
    ChangesRequested,
    #[serde(rename = "done")]
    Done,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "canceled")]
    Canceled,
    // Legacy statuses (backward compatibility)
    #[serde(rename = "backlog")]
    Backlog,
    #[serde(rename = "planning")]
    Planning,
    #[serde(rename = "in_progress")]
    InProgress,
    #[serde(rename = "awaiting_review")]
    AwaitingReview,
    #[serde(rename = "pr_created")]
    PrCreated,
}

impl TaskStatus {
    /// Returns the string representation matching the database/API value.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Draft => "draft",
            Self::Refining => "refining",
            Self::PendingApproval => "pending_approval",
            Self::Approved => "approved",
            Self::Coding => "coding",
            Self::PlanReview => "plan_review",
            Self::Review => "review",
            Self::MergeConflicts => "merge_conflicts",
            Self::ChangesRequested => "changes_requested",
            Self::Done => "done",
            Self::Failed => "failed",
            Self::Canceled => "canceled",
            Self::Backlog => "backlog",
            Self::Planning => "planning",
            Self::InProgress => "in_progress",
            Self::AwaitingReview => "awaiting_review",
            Self::PrCreated => "pr_created",
        }
    }
}

impl std::fmt::Display for TaskStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl std::str::FromStr for TaskStatus {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "draft" => Ok(Self::Draft),
            "refining" => Ok(Self::Refining),
            "pending_approval" => Ok(Self::PendingApproval),
            "approved" => Ok(Self::Approved),
            "coding" => Ok(Self::Coding),
            "plan_review" => Ok(Self::PlanReview),
            "review" => Ok(Self::Review),
            "merge_conflicts" => Ok(Self::MergeConflicts),
            "changes_requested" => Ok(Self::ChangesRequested),
            "done" => Ok(Self::Done),
            "failed" => Ok(Self::Failed),
            "canceled" => Ok(Self::Canceled),
            "backlog" => Ok(Self::Backlog),
            "planning" => Ok(Self::Planning),
            "in_progress" => Ok(Self::InProgress),
            "awaiting_review" => Ok(Self::AwaitingReview),
            "pr_created" => Ok(Self::PrCreated),
            other => Err(format!("unknown task status: '{other}'")),
        }
    }
}

/// Complete Task entity with all fields from the two-agent workflow.
///
/// Maps 1:1 to the `tasks` SQLite table. JSON fields (context_files,
/// changes_data, conflict_files) are stored as TEXT in the database.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Task {
    /// Unique identifier (UUID).
    pub id: String,

    // -- Legacy fields (still supported) --
    /// Short feature name.
    pub title: String,
    /// Detailed description (prompt for agent).
    pub description: String,
    /// Repository URL (e.g., https://github.com/user/repo).
    pub repo_url: String,
    /// Base branch for the task (default: "main").
    pub target_branch: String,
    /// Files the agent should review first (JSON array in DB).
    pub context_files: Vec<String>,
    /// Build command to verify changes.
    pub build_command: Option<String>,

    // -- Two-agent workflow fields --
    /// Link to the repositories table.
    pub repository_id: Option<String>,
    /// Raw user idea/request (Step 1 - Draft).
    pub user_input: Option<String>,
    /// Spec generated by PM Agent (Step 2 - Spec Generation, markdown).
    pub generated_spec: Option<String>,
    /// ISO timestamp when the spec was generated.
    pub generated_spec_at: Option<String>,
    /// Final approved spec, may be edited by user (Step 3 - Approval).
    pub final_spec: Option<String>,
    /// ISO timestamp when the spec was approved.
    pub spec_approved_at: Option<String>,
    /// True if the user modified the generated spec before approving.
    pub was_spec_edited: bool,
    /// Branch name created by Dev Agent (Step 4 - Coding).
    pub branch_name: Option<String>,
    /// PR number on GitHub.
    pub pr_number: Option<i64>,

    /// CLI agent type override for this task.
    pub agent_type: Option<String>,
    /// CLI agent model override for this task.
    pub agent_model: Option<String>,
    /// Persisted changes/diff data (JSON) so diffs survive worktree cleanup.
    pub changes_data: Option<String>,
    /// JSON array of file paths with merge conflicts.
    pub conflict_files: Option<String>,
    /// Commit hash captured when agent execution starts, used as diff base.
    pub base_commit: Option<String>,

    // -- Status and metadata --
    /// Current status of the task.
    pub status: TaskStatus,
    /// URL of the created PR.
    pub pr_url: Option<String>,
    /// Error message if the task failed.
    pub error: Option<String>,

    /// ISO timestamp when the task was created.
    pub created_at: String,
    /// ISO timestamp when the task was last updated.
    pub updated_at: String,
}

/// Input for creating a new task in the two-agent workflow.
///
/// The user provides a repository and a simple idea/request. Legacy fields
/// are accepted for backward compatibility but are optional.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateTaskInput {
    /// Required: selected repository UUID.
    pub repository_id: String,
    /// Required: user's idea/request text.
    pub user_input: String,

    // Optional legacy fields for backward compatibility
    pub title: Option<String>,
    pub description: Option<String>,
    pub repo_url: Option<String>,
    #[serde(default = "default_branch")]
    pub target_branch: Option<String>,
    #[serde(default)]
    pub context_files: Option<Vec<String>>,
    pub build_command: Option<String>,
    pub agent_type: Option<String>,
    pub agent_model: Option<String>,
}

fn default_branch() -> Option<String> {
    Some("main".to_string())
}

/// Input for updating an existing task. All fields are optional.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct UpdateTaskInput {
    pub title: Option<String>,
    pub description: Option<String>,
    pub repo_url: Option<String>,
    pub target_branch: Option<String>,
    pub context_files: Option<Vec<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub build_command: Option<Option<String>>,
    pub status: Option<TaskStatus>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub pr_url: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub pr_number: Option<Option<i64>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub branch_name: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub error: Option<Option<String>>,

    // Two-agent workflow fields
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub user_input: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub generated_spec: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub generated_spec_at: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub final_spec: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub spec_approved_at: Option<Option<String>>,
    pub was_spec_edited: Option<bool>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub repository_id: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub agent_type: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub agent_model: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub changes_data: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub conflict_files: Option<Option<String>>,
    /// Nullable: `Some(None)` means explicitly set to NULL.
    pub base_commit: Option<Option<String>>,
}
